graph TD

    User

    subgraph F5
        direction TB
        VS["Virtual Server"]
        %% note "F5 Load Balancer" right of VS
        %%     """
        %%     - Two nodes are configured as a pool with Active/Standby mode
        %%     - Use a configure file in the NAS to member two nodes' role.
        %%     - Active node is the default target for all requests.
        %%     - Standby node is used if the active node is down.
        %%     """
        %% end
    end



    Active["Jenkins Active Node"]

    subgraph "Jenkins Standby Node"
        direction TB
        Standby["Jenkins Standby Node"]
        Service["Service\nBy default, the Jenkins service is stopped."]
        Script["Script\nRun a script via crontab.\n- Checks active node status.\n- If down, starts Jenkins on standby (unless in maintenance).\n- Switches standby/active in a configure file in the NAS.\n- Logs status for review."]
    end

    NAS["NAS (JENKINS_HOME)"]
    User -->|Access with https/443| VS
    BYOA -->|Connect with Tcp/7788| VS
    VS -->|Https/443 and Tcp/7788 request by default| Active
    F5 -->|Health Check| Active
    VS -.->|Https/443 and Tcp/7788 requests if active node is down| Standby
    F5 -->|Health Check| Standby
    Script -->|Monitor Jenkins service status| Active
    %% note right of Active
    %%     """
    %%     The monitor script runs on both machines.
    %%     """
    %% end
    Active -->|Read/Write| NAS
    Standby -->|Read/Write| NAS
