@startuml Jenkins HA with F5 Load Balancer
title Jenkins High Availability with F5 Load Balancer

actor User
node BYOA

rectangle "F5 Load Balancer" as F5 #MintCream;line:Orange;text:MidnightBlue {
    node "Virtual Server" as VS #MintCream;line:Orange;text:MidnightBlue 
    note right of VS
        - Two nodes are configured as a pool with Active/Standby mode.
        - A configuration file in the NAS defines the roles of the two nodes.
        - The Active node is the default target for all requests.
        - The Standby node is used if the Active node is down.
    end note
}

node "Jenkins Active Node" as Active #palegreen;line:green;text:green

node "Jenkins Standby Node" as Standby #aliceblue;line:blue;line.dotted;text:blue {
    rectangle service #aliceblue;line:blue;text:blue [
        By default, the Jenkins service is stopped.
        - Runs a script via cron.
        - Checks Active node status.
        - If down, starts Jenkins on Standby (unless in maintenance).
        - Updates role in the NAS configuration file.
        - Logs status for review.
    ]
}

folder "NAS (JENKINS_HOME)" as NAS #linen;line:navy;text:navy

User --> VS : Access via HTTPS (Port 443)
BYOA --> VS : Connect via TCP (Port 7788)

VS --> Active #green;text:green : HTTPS (Port 443) and TCP (Port 7788) requests by default
F5 --> Active #Orange;text:Orange : Health Check
VS --> Standby #blue;line.dotted;text:blue : HTTPS and TCP requests if Active node is down
F5 --> Standby #Orange;text:Orange : Health Check

service --> Active #blue;text:blue : Monitors Jenkins service status
note right of Active
    The monitoring script runs on both machines.
end note
Active -[#navy]> NAS : Read/Write
Standby -[#navy]> NAS : Read/Write

@enduml
