apiVersion: v1
kind: Pod
metadata:
  name: python-pod
spec:
  containers:
  - name: python
    image: python:3.8
    command: ['cat']
    tty: true
  - name: jnlp
    image: your-custom-jnlp-image:latest
    args: ['$(JENKINS_SECRET)', '$(JENKINS_NAME)']
    env:
    - name: JENKINS_SECRET
      valueFrom:
        secretKeyRef:
          name: jenkins-secret
          key: jnlp-secret
    - name: JENKINS_NAME
      valueFrom:
        secretKeyRef:
          name: jenkins-secret
          key: jnlp-name
